Repository itggot-TE4/Fire-experts, pull requests merged in 2020-10, with the labels that each got.

#17 Ci/2 eslint
  .eslintrc.yml
  .github/workflows/tests.yml
  package-lock.json
  package.json
  yarn.lock
Labels: type:CI

#19 Linked materialize and google fonts
  public/index.html
Labels: type:feature

#22 Added Sinatra backend, with hardcoded values
  Gemfile
  Gemfile.lock
  config.ru
  server.rb
Labels: type:feature

#25 Added dynamic API fetcher to backend
  Gemfile
  Gemfile.lock
  config.ru
  server.rb
Labels: type:bug

#31 Fix of invalid GET route
  server.rb
Labels: type:bug

#32 Update of readme
  README.md
Labels: type:documentation

#40 Feature/38 fetch from backend
  public/js/main.js
Labels: type:feature

#41 Release of v0.1.0
  .eslintrc.yml
  .github/workflows/tests.yml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  config.ru
  package-lock.json
  package.json
  public/css/main.css
  public/index.html
  public/js/main.js
  server.rb
  yarn.lock
Labels: type:release

#45 Implemented fork cards
  public/index.html
  public/js/main.js
Labels: type:feature

#64 Changed highlighting style to dark mode
  .eslintignore
  public/css/styles/monokai.css
  public/css/styles/pojoaque.jpg
  public/css/styles/school-book.png
  public/index.html
  public/js/highlight.pack.js
Labels: type:improvement

#52 Added GH superlinter
  .github/linters/.rubocop.yml
  .github/workflows/tests.yml
  public/css/main.css
  server.rb
Labels: type:CI

#61 Added dynamic syntax highlighting
  public/index.html
  public/js/main.js
Labels: type:feature

#65 Fixed linter configuration
  .eslintignore
  .eslintrc.yml
  .github/workflows/tests.yml
  .rubocop.yml
  .stylelintrc.json
Labels: type:CI

#70 Make radiobuttons work again
  public/index.html
Labels: type:bug

#50 Release of v1.0.0
  .eslintrc.yml
  .github/workflows/tests.yml
  .rubocop.yml
  .stylelintrc.json
  README.md
  public/css/main.css
  public/css/styles/monokai.css
  public/css/styles/pojoaque.jpg
  public/css/styles/school-book.png
  public/img/favicon.ico
  public/index.html
  public/js/highlight.pack.js
  public/js/main.js
  server.rb
Labels: type:release

#80 Added GitHub login
  Gemfile
  Gemfile.lock
  public/css/main.css
  public/img/GitHub_logo.png
  public/index.html
  public/js/main.js
  server.rb
  views/index.slim
  views/layout.slim
Labels: type:feature

#84 Updated documentation title
  docs/index.html
Labels: type:documentation

#85 Gives a accent color to the card if it does not contain a manifest file
  public/css/main.css
  public/js/main.js
Labels: type:feature

#88 Dynamically test JS code
  public/css/main.css
  public/js/main.js
Labels: type:feature

#89 Added acceptance tests
  .github/workflows/tests.yml
  Gemfile
  Gemfile.lock
  rakefile
  spec/acceptance/acceptance_helper.rb
  spec/acceptance/test_spec.rb
  spec/spec_helper.rb
Labels: type:CI, type:test

#86 v1.1.0
  .github/workflows/tests.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  db/db.db
  db/seed.rb
  docs/README.md
  docs/_navbar.md
  docs/index.html
  modules/dbhandler.rb
  public/css/main.css
  public/img/GitHub_logo.png
  public/index.html
  public/js/main.js
  rakefile
  server.rb
  spec/acceptance/acceptance_helper.rb
  spec/acceptance/test_spec.rb
  spec/spec_helper.rb
  views/index.slim
  views/layout.slim
Labels: type:release
